//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FloorplanLocation
    {
        public long FloorplanLocationId { get; set; }
        public string Description { get; set; }
        public string MinX { get; set; }
        public string MaxX { get; set; }
        public string MinY { get; set; }
        public string MaxY { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> AddedByUserProfileId { get; set; }
        public Nullable<long> ModifiedByUserProfileId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> FloorplanId { get; set; }
    
        public virtual Floorplan Floorplan { get; set; }
        public virtual Location Location { get; set; }
    }
}
