//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int PropertyId { get; set; }
        public int ContractId { get; set; }
        public string PropertyNumber { get; set; }
        public string AssetNumber { get; set; }
        public string Address { get; set; }
        public string PropertyArea { get; set; }
        public int PropertyTypeId { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public Nullable<int> Floorplan { get; set; }
    }
}
